version: '3'

volumes:
  postgres_data:
      driver: local

services:
#  postgres:
#      image: postgres
      #volumes:
      #  - /home/dimitar/docker_volumes/dimitar_keycloak_11:/var/lib/postgresql/data
#      environment:
#        POSTGRES_DB: keycloak
#        POSTGRES_USER: keycloak
#        POSTGRES_PASSWORD: password
#      ports:
#        - 5433:5432
  keycloak:
      image: quay.io/keycloak/keycloak:19.0.3-legacy
      volumes:
        - ./jhipsterrealm.json:/tmp/jhipsterrealm.json
      environment:
 #       DB_VENDOR: POSTGRES
 #       DB_ADDR: postgres
 #       DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
        KEYCLOAK_IMPORT: "/tmp/jhipsterrealm.json"
        KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI: "true" 
        # JAVA_TOOL_OPTIONS: '-Djboss.http.port=9080' #to change default port, needed if you run with docker compose!
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 9080:8080
#      depends_on:
#        - postgres
